[package]
name = "bdk-ffi"
version = "0.9.0"
authors = ["Steve Myers <steve@notmandatory.org>", "Sudarsan Balaji <sudarsan.balaji@artfuldev.com>"]
edition = "2018"

[workspace]
members = [".","bdk-ffi-bindgen"]
default-members = [".", "bdk-ffi-bindgen"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["staticlib", "cdylib"]
name = "bdkffi"

[dependencies]
bdk = { version = "0.22", features = ["all-keys", "use-esplora-ureq", "sqlite-bundled"] }

uniffi_macros = { version = "0.20.0", features = ["builtin-bindgen"] }
uniffi = { version = "0.20.0", features = ["builtin-bindgen"] }

[build-dependencies]
uniffi_build = { version = "0.20.0", features = ["builtin-bindgen"] }
