name: Build JVM and Android API Docs Websites

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Set up JDK 17"
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17

      - name: "Build JVM API documentation"
        run: |
          cd ./bdk-jvm/
          bash ./scripts/build-linux-x86_64.sh
          ./gradlew dokkaHtml
      
      - name: "Upload JVM website"
        uses: actions/upload-artifact@v4
        with:
          name: artifact-jvm-api-docs
          path: /home/runner/work/bdk-ffi/bdk-ffi/bdk-jvm/lib/build/dokka/html/

      - name: "Build Android API documentation"
        run: |
          cd ./bdk-android/
          bash ./scripts/build-linux-x86_64.sh
          ./gradlew dokkaHtml

      - name: "Upload Android website"
        uses: actions/upload-artifact@v3
        with:
          name: artifact-android-api-docs
          path: /home/runner/work/bdk-ffi/bdk-ffi/bdk-android/lib/build/dokka/html/
  